---
language: python
services: docker

env:
  global:
    - ROLE_NAME: solr
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian10

    # Solr 7.
    - MOLECULE_DISTRO: centos7
      MOLECULE_PLAYBOOK: playbook-solr-7.yml
    - MOLECULE_DISTRO: debian10
      MOLECULE_PLAYBOOK: playbook-solr-7.yml

    # Solr 6.
    - MOLECULE_DISTRO: ubuntu1604
      MOLECULE_PLAYBOOK: playbook-solr-6.yml

    # Solr 5.
    - MOLECULE_DISTRO: ubuntu1604
      MOLECULE_PLAYBOOK: playbook-solr-5.yml

    # Solr 4.
    - MOLECULE_DISTRO: ubuntu1604
      MOLECULE_PLAYBOOK: playbook-solr-4.yml

    # Solr 3.
    - MOLECULE_DISTRO: ubuntu1604
      MOLECULE_PLAYBOOK: playbook-solr-3.yml

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME geerlingguy.$ROLE_NAME
  - cd geerlingguy.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
