---
dependencies: []

galaxy_info:
  author: geerlingguy
  description: Varnish for Linux.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
        - bionic
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - web
    - varnish
    - cache
    - proxy
    - reverse
    - performance
    - loadbalancer
    - balancer
