---

galaxy_name: weareinteractive.newrelic
github_user: weareinteractive
github_name: ansible-newrelic
badges: |
  [![Build Status](https://img.shields.io/travis/weareinteractive/ansible-newrelic.svg)](https://travis-ci.org/weareinteractive/ansible-newrelic)
  [![Galaxy](http://img.shields.io/badge/galaxy-weareinteractive.newrelic-blue.svg)](https://galaxy.ansible.com/weareinteractive/newrelic/)
  [![GitHub Tags](https://img.shields.io/github/tag/weareinteractive/ansible-newrelic.svg)](https://github.com/weareinteractive/ansible-newrelic)
  [![GitHub Stars](https://img.shields.io/github/stars/weareinteractive/ansible-newrelic.svg)](https://github.com/weareinteractive/ansible-newrelic)
description: |
  > * installs newrelic
  > * configures newrelic
  > * configures service

  **Note:**

  > Since Ansible Galaxy supports [organization](https://www.ansible.com/blog/ansible-galaxy-2-release) now, this role has moved from `franklinkim.newrelic` to `weareinteractive.newrelic`!
