---
roles:
  - name: arknoll.selenium
    version: 2.2.2
  - name: thom8.php-upload-progress
    version: 1.0.1
  - name: weareinteractive.newrelic
    version: 1.8.0
  - name: geerlingguy.adminer
    version: 1.2.0
  - name: geerlingguy.apache
    version: 3.1.0
  - name: geerlingguy.apache-php-fpm
    version: 1.1.0
  - name: geerlingguy.blackfire
    version: 1.1.3
  - name: geerlingguy.composer
    version: 1.7.6
  - name: geerlingguy.daemonize
    version: 1.2.1
  - name: geerlingguy.drupal
    version: 3.0.1
  - name: geerlingguy.drupal-console
    version: 1.1.1
  - name: geerlingguy.drush
    version: 3.1.2
  - name: geerlingguy.elasticsearch
    version: 4.1.1
  - name: geerlingguy.firewall
    version: 2.4.3
  - name: geerlingguy.git
    version: 2.1.0
  - name: geerlingguy.java
    version: 1.9.7
  - name: geerlingguy.mailhog
    version: 2.2.0
  - name: geerlingguy.memcached
    version: 1.0.8
  - name: geerlingguy.mysql
    version: 3.1.0
  - name: geerlingguy.nginx
    version: 2.7.0
  - name: geerlingguy.nodejs
    version: 5.1.1
  - name: geerlingguy.php
    version: 4.2.0
  - name: geerlingguy.php-memcached
    version: 2.0.2
  - name: geerlingguy.php-mysql
    version: 2.0.2
  - name: geerlingguy.php-pecl
    version: 2.0.0
  - name: geerlingguy.php-pgsql
    version: 1.0.1
  - name: geerlingguy.php-redis
    version: 3.2.1
  - name: geerlingguy.php-tideways
    version: 2.2.0
  - name: geerlingguy.php-versions
    version: 4.0.3
  - name: geerlingguy.php-xdebug
    version: 3.0.0
  - name: geerlingguy.php-xhprof
    version: 3.0.0
  - name: geerlingguy.pimpmylog
    version: 1.0.2
  - name: geerlingguy.postfix
    version: 2.0.0
  - name: geerlingguy.postgresql
    version: 2.2.0
  - name: geerlingguy.redis
    version: 1.6.0
  - name: geerlingguy.repo-remi
    version: 1.2.0
  - name: geerlingguy.ruby
    version: 2.6.0
  - name: geerlingguy.security
    version: 1.9.0
  - name: geerlingguy.solr
    version: 5.0.0
  - name: geerlingguy.varnish
    version: 3.0.3
